-- 物料字典
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_LSWLZD' AND xtype = 'V')
	DROP VIEW v_SUF_LSWLZD
GO

CREATE VIEW v_SUF_LSWLZD
AS
	SELECT t1.LSWLZD_WLBH AS ID,t1.*
	,t1.LSWLZD_JLDW AS JBJLDW -- 基本计量单位
	,CASE t1.LSWLZD_CKFS WHEN 0 THEN 0 ELSE 1 END AS SFQYPCGL --是否启用批次管理 0:正常出库;1:先进先出;2:后进先出;3:人工选择;
	,CASE t1.LSWLZD_CKFS WHEN 0 THEN 0 ELSE 1 END AS SFQYBZQGL --是否启用保质期,跟是否管理批次一样;
	,'' AS FF_CKBH,'' AS FF_HWBH
	FROM LSWLZD t1
GO

-- 库存货位字典
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCHWZD' AND xtype = 'V')
	DROP VIEW v_SUF_KCHWZD
GO

CREATE VIEW v_SUF_KCHWZD
AS
	SELECT t1.KCHWZD_HWBH AS ID,t1.* FROM KCHWZD t1
	UNION 
	SELECT '0','*','*','','','1','1','','0','0'
GO

-- 即时库存
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_JXC_CKYE_SSYE' AND xtype = 'V')
	DROP VIEW v_SUF_JXC_CKYE_SSYE
GO
CREATE VIEW v_SUF_JXC_CKYE_SSYE
AS
	SELECT t1.FF_WLBH+'|'+t1.FF_CKBH+'|'+t1.FF_PCH+'|'+t1.FF_HWBH+'|'+t1.FF_WLZT+'|'+t1.FF_WLBZ+'|'+t1.FF_TSKC+'|'+t1.FF_XGDX+'|'+t1.FF_ZYX1+'|'+t1.FF_ZYX2+'|'+t1.FF_ZYX3+'|'+t1.FF_ZYX4+'|'+t1.FF_ZYX5 AS ID
	,t1.FF_WLBH,t1.FF_CKBH,t1.FF_PCH
	,CASE t1.FF_HWBH WHEN '' THEN '0' ELSE t1.FF_HWBH END AS FF_HWBH
	,t1.FF_WLZT,t1.FF_WLBZ,t1.FF_TSKC,t1.FF_XGDX,t1.FF_ZYX1,t1.FF_ZYX2,t1.FF_ZYX3,t1.FF_ZYX4,t1.FF_ZYX5,t1.FF_SLYE,t1.FF_FSLYE1,t1.FF_FSLYE2,t1.FF_JEYE
	,t2.LSWLZD_JLDW AS JLDW,t2.JBJLDW AS JBJLDW,t1.FF_SLYE AS JBDWSL -- 基本单位数量
	FROM JXC_CKYE_SSYE t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.FF_WLBH=t2.LSWLZD_WLBH
	WHERE FF_SLYE>=0 -- 数量余额>=0
GO

-- 存放位置
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_CFWZ' AND xtype = 'V')
	DROP VIEW v_SUF_CFWZ
GO
CREATE VIEW v_SUF_CFWZ
AS
	SELECT CKID+'|'+HWID AS ID,'CK'+CKNumber+'|CW'+HWNumber AS CFWZNumber,'CK'+CKName+'|CW'+HWName AS CFWZName
	,CKID,CKNumber,CKName,HWID,HWNumber,HWName
	FROM(
		SELECT t1.LSCKZD_CKBH AS CKID,t1.LSCKZD_CKBH AS CKNumber,t1.LSCKZD_CKMC AS CKName,'0' AS HWID,'*' AS HWNumber,'*' AS HWName
		FROM LSCKZD t1
		LEFT JOIN KCHWZD t2 ON t1.LSCKZD_CKBH=t2.KCHWZD_CKBH
		WHERE t1.LSCKZD_CKZT=0--正常状态
		AND t1.LSCKZD_MX=1--是否为明细，明细才能在业务中使用
		AND t2.KCHWZD_HWBH IS NULL
		UNION
		SELECT t1.LSCKZD_CKBH AS CKID,t1.LSCKZD_CKBH AS CKNumber,t1.LSCKZD_CKMC AS CKName,t2.KCHWZD_HWBH AS HWID,t2.KCHWZD_HWBH AS HWNumber,t2.KCHWZD_HWMC AS HWName
		FROM LSCKZD t1
		INNER JOIN KCHWZD t2 ON t1.LSCKZD_CKBH=t2.KCHWZD_CKBH
		WHERE t1.LSCKZD_CKZT=0--正常状态
		AND t1.LSCKZD_MX=1--是否为明细，明细才能在业务中使用
	) table1
GO

-- 用途
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCYTZD' AND xtype = 'V')
	DROP VIEW v_SUF_KCYTZD
GO

CREATE VIEW v_SUF_KCYTZD
AS
	SELECT t1.KCYTZD_YTBH AS ID
	,t1.KCYTZD_YTBH
	,t1.KCYTZD_YTMC
	,t1.KCYTZD_JS
	,t1.KCYTZD_MX
	FROM KCYTZD	 t1
	WHERE  t1.KCYTZD_MX=1--是否为明细，明细才能在业务中使用
GO

-- 部门字典
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCBMZD' AND xtype = 'V')
	DROP VIEW v_SUF_KCBMZD
GO

CREATE VIEW v_SUF_KCBMZD
AS
	SELECT t1.KCBMZD_BMBH AS ID
	,t1.KCBMZD_BMBH
	,t1.KCBMZD_BMMC
	,t1.KCBMZD_JS
	,t1.KCBMZD_MX
	,t1.KCBMZD_HSBM
	,t1.KCBMZD_YB
	,t1.KCBMZD_DZ
	,t1.KCBMZD_DH
	,t1.KCBMZD_FZR
	,t1.KCBMZD_LXR
	,t1.KCBMZD_EML
	,t1.KCBMZD_DYTMH
	,t1.KCBMZD_SFFC
	FROM KCBMZD  t1
	WHERE  t1.KCBMZD_MX=1--是否为明细，明细才能在业务中使用
GO

-- 销售提单
-- SELECT * FROM PPITEM WHERE PPITEM_ZDLX='DATE' AND PPITEM_XXJDM='BZHSTD' -- 日期字段查询参考
-- SELECT * FROM dbo.T_SUFI_Schema_BillInfo WHERE FDataType=103 AND FBillKey='BZHSTD' -- 日期字段查询参考2（优先参考）
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_XSTD' AND xtype = 'V')
	DROP VIEW v_SUF_XSTD
GO
CREATE VIEW v_SUF_XSTD
AS
	SELECT t1.XSTD_TDLS AS ID,t1.XSTD_PJLX,t1.XSTD_YWBS,t1.XSTD_ZBPJLX,t1.XSTD_TDBH,dbo.F_SUF_DateStr2Date(t1.XSTD_DJRQ) AS XSTD_DJRQ
	,dbo.F_SUF_DateStr2Date(t1.XSTD_YWRQ) AS XSTD_YWRQ,dbo.F_SUF_DateStr2Date(t1.XSTD_XGSJ) AS XSTD_XGSJ,t1.XSTD_QCBZ
	,t1.XSTD_TDBZ,t1.XSTD_YWBH,t1.XSTD_ZLBH,t1.XSTD_SHDKH,t1.XSTD_SHDKHMC,t1.XSTD_SODKH,t1.XSTD_SODKHMC,t1.XSTD_SPKH,t1.XSTD_SPKHMC
	,t1.XSTD_FKKH,t1.XSTD_FKKHMC,t1.XSTD_ADDR,t1.XSTD_TELE,t1.XSTD_LXR,t1.XSTD_BMBH,t1.XSTD_RYBH,t1.XSTD_WBBH,t1.XSTD_HL,t1.XSTD_HTBH
	,t1.XSTD_HTLS,t1.XSTD_ZKZC,dbo.F_SUF_DateStr2Date(t1.XSTD_HKRQ) AS XSTD_HKRQ,t1.XSTD_FSBH,t1.XSTD_DHDD,t1.XSTD_ZDXM,t1.XSTD_JZBZ
	,dbo.F_SUF_DateStr2Date(t1.XSTD_JZSJ) AS XSTD_JZSJ,t1.XSTD_JZXM,t1.XSTD_PZNM
	,dbo.F_SUF_DateStr2Date(t1.XSTD_PZRQ) AS XSTD_PZRQ,t1.XSTD_PZBH,t1.XSTD_PZND,t1.XSTD_SFQR,t1.XSTD_SFJZ,t1.XSTD_SFQXJZ,t1.XSTD_SFXG,t1.XSTD_SFSC,t1.XSTD_SFLS,t1.XSTD_SFCZX
	,t1.XSTD_SFCDJ,t1.XSTD_DYDATE,t1.XSTD_DYPERSON,t1.XSTD_SHLC,t1.XSTD_SHBZ,t1.XSTD_SHRQ,t1.XSTD_SHXM,t1.XSTD_C1,t1.XSTD_C2,t1.XSTD_C3
	,t1.XSTD_C4,t1.XSTD_C5,t1.XSTD_C6,t1.XSTD_C7,t1.XSTD_C8,t1.XSTD_C9,t1.XSTD_C10,t1.XSTD_U1,t1.XSTD_U2,t1.XSTD_U3,t1.XSTD_U4,t1.XSTD_U5
	,t1.XSTD_U6,t1.XSTD_BZ
	FROM XSTD t1
GO

-- 销售提单明细
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_XSTDMX' AND xtype = 'V')
	DROP VIEW v_SUF_XSTDMX
GO
CREATE VIEW v_SUF_XSTDMX
AS
	SELECT t1.XSTDMX_TDLS AS ID,t1.XSTDMX_TDFL AS EntryID,t1.XSTDMX_XSXH,t1.XSTDMX_FLLX,t1.XSTDMX_FLLY,t1.XSTDMX_KCFS,t1.XSTDMX_DDLS,t1.XSTDMX_DDFL
	,t1.XSTDMX_DDBH,t1.XSTDMX_YTDLS,t1.XSTDMX_YTDFL,t1.XSTDMX_YTDBH,t1.XSTDMX_HTLS,t1.XSTDMX_HTFL,t1.XSTDMX_ECTDLS,t1.XSTDMX_ECTDFL
	,t1.XSTDMX_ECDDLS,t1.XSTDMX_ECDDFL,t1.XSTDMX_ECRKLS,t1.XSTDMX_ECRKFL,dbo.F_SUF_DateStr2Date(t1.XSTDMX_JHRQ) AS XSTDMX_JHRQ,t1.XSTDMX_CKBH,t1.XSTDMX_WLBH,t1.XSTDMX_PCH
	,t1.XSTDMX_HWBH,t1.XSTDMX_ZYX1,t1.XSTDMX_ZYX2,t1.XSTDMX_ZYX3,t1.XSTDMX_ZYX4,t1.XSTDMX_ZYX5,t1.XSTDMX_WLZT,t1.XSTDMX_WLBZ
	,t1.XSTDMX_ZSL,t1.XSTDMX_FSL1,t1.XSTDMX_FSL2,t1.XSTDMX_YZHSJ,t1.XSTDMX_BZHSJ,t1.XSTDMX_YZXSJ,t1.XSTDMX_BZXSJ,t1.XSTDMX_SL
	,t1.XSTDMX_YXSE,t1.XSTDMX_BXSE,t1.XSTDMX_YSE,t1.XSTDMX_BSE,t1.XSTDMX_YHSE,t1.XSTDMX_BHSE,t1.XSTDMX_DBZKBL,t1.XSTDMX_ZEZKBL
	,t1.XSTDMX_YZKJE,t1.XSTDMX_BZKJE,t1.XSTDMX_YZSL,t1.XSTDMX_YFSL,t1.XSTDMX_YFSL1,t1.XSTDMX_YFSL2,t1.XSTDMX_SFFY,t1.XSTDMX_SFKP
	,t1.XSTDMX_KPBZ,t1.XSTDMX_KPSL,t1.XSTDMX_KPFSL1,t1.XSTDMX_KPFSL2,t1.XSTDMX_YKPE,t1.XSTDMX_BKPE,t1.XSTDMX_SFCK,t1.XSTDMX_CKBZ
	,t1.XSTDMX_CKSL,t1.XSTDMX_CKFSL1,t1.XSTDMX_CKFSL2,t1.XSTDMX_THSL,t1.XSTDMX_THFSL1,t1.XSTDMX_THFSL2,t1.XSTDMX_BHSL,t1.XSTDMX_BHFSL1
	,t1.XSTDMX_BHFSL2,t1.XSTDMX_SFTH,t1.XSTDMX_THBZ,t1.XSTDMX_KCYL,t1.XSTDMX_DDKCYL,t1.XSTDMX_BZ,t1.XSTDMX_C1,t1.XSTDMX_C2
	,t1.XSTDMX_C3,t1.XSTDMX_C4,t1.XSTDMX_C5,t1.XSTDMX_C6,t1.XSTDMX_C7,t1.XSTDMX_C8,t1.XSTDMX_C9,t1.XSTDMX_C10,t1.XSTDMX_U1,t1.XSTDMX_U2
	,t1.XSTDMX_U3,t1.XSTDMX_U4,t1.XSTDMX_U5,t1.XSTDMX_U6,t1.XSTDMX_DQZK,t1.XSTDMX_YJBZ,t1.XSTDMX_YLZSL,t1.XSTDMX_YLFSL1,t1.XSTDMX_YLFSL2
	,t1.XSTDMX_YHZSL,t1.XSTDMX_YHFSL1,t1.XSTDMX_YHFSL2,t1.XSTDMX_YSTDLS,t1.XSTDMX_YSTDFL,t1.XSTDMX_LZRQ,dbo.F_SUF_DateStr2Date(t1.XSTDMX_YHKRQ) AS XSTDMX_YHKRQ
	,t1.XSTDMX_ZXPDYJ,t1.XSTDMX_ZXTSZC,t1.XSTDMX_YYWRQ,t1.XSTDMX_DCZSL,t1.XSTDMX_DCFSL1,t1.XSTDMX_DCFSL2,t1.XSTDMX_YDCE,t1.XSTDMX_BDCE
	,t1.XSTDMX_SFHK,t1.XSTDMX_HKBZ,t1.XSTDMX_HKSL,t1.XSTDMX_YHKE,t1.XSTDMX_BHKE,t1.XSTDMX_HKFSL1,t1.XSTDMX_HKFSL2,t1.XSTDMX_YKPCE
	,t1.XSTDMX_BKPCE,t1.XSTDMX_YCEHXE,t1.XSTDMX_BCEHXE,t1.XSTDMX_BCYHSL,t1.XSTDMX_PHHZ,t1.XSTDMX_JGYS,t1.XSTDMX_JGZC,t1.XSTDMX_GBSL
	,t1.XSTDMX_CZYC,t1.XSTDMX_SFZJ,t1.XSTDMX_JSSL,t1.XSTDMX_FJSSL1,t1.XSTDMX_FJSSL2,t1.XSTDMX_ZJZT,t1.XSTDMX_BGDH
	,t1.XSTDMX_ZSL AS JBDWSL -- 基本单位数量
	,t2.LSWLZD_JLDW AS JLDW -- 计量单位
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	FROM XSTDMX t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.XSTDMX_WLBH=t2.LSWLZD_WLBH
GO

-- 库存出库单1
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCCKD1' AND xtype = 'V')
	DROP VIEW v_SUF_KCCKD1
GO
CREATE VIEW v_SUF_KCCKD1
AS
	SELECT t1.KCCKD1_PJLX,t1.KCCKD1_LSBH AS ID,dbo.F_SUF_DateStr2Date(t1.KCCKD1_DJRQ) AS KCCKD1_DJRQ,dbo.F_SUF_DateStr2Date(t1.KCCKD1_KCYWRQ) AS KCCKD1_KCYWRQ,dbo.F_SUF_DateStr2Date(t1.KCCKD1_CHYWRQ) AS KCCKD1_CHYWRQ,t1.KCCKD1_SJDH,t1.KCCKD1_LBBH
	,t1.KCCKD1_CKBH,t1.KCCKD1_BMBH,t1.KCCKD1_YTBH,t1.KCCKD1_JHBH,t1.KCCKD1_CPBH,t1.KCCKD1_CPSL,t1.KCCKD1_XEDH,t1.KCCKD1_CPPC
	,t1.KCCKD1_FZR,t1.KCCKD1_LYR,t1.KCCKD1_LRXM,t1.KCCKD1_BGY,t1.KCCKD1_THDH,t1.KCCKD1_DWMC,t1.KCCKD1_DWBH,t1.KCCKD1_DHDD
	,t1.KCCKD1_YWBS,t1.KCCKD1_LYBZ,t1.KCCKD1_LYBH,t1.KCCKD1_SFJCHZ,t1.KCCKD1_YLDRBZ,t1.KCCKD1_BZ,t1.KCCKD1_KCJZ,t1.KCCKD1_CHJZ
	,t1.KCCKD1_CHXM,t1.KCCKD1_HDBZ,t1.KCCKD1_CBBZ,dbo.F_SUF_DateStr2Date(t1.KCCKD1_PZRQ) AS KCCKD1_PZRQ,t1.KCCKD1_PZNM,t1.KCCKD1_PZND,t1.KCCKD1_PZBH,t1.KCCKD1_CXBH
	,t1.KCCKD1_SCJZBZ,t1.KCCKD1_SCJZR,dbo.F_SUF_DateStr2Date(t1.KCCKD1_SCJZRQ) AS KCCKD1_SCJZRQ,t1.KCCKD1_SHLC,t1.KCCKD1_SHBZ,t1.KCCKD1_SHRQ,t1.KCCKD1_SHXM,t1.KCCKD1_QCBZ
	,t1.KCCKD1_GXTD,t1.KCCKD1_DWGC,dbo.F_SUF_DateStr2Date(t1.KCCKD1_KCXGSJ) AS KCCKD1_KCXGSJ,dbo.F_SUF_DateStr2Date(t1.KCCKD1_CHXGSJ) AS KCCKD1_CHXGSJ,dbo.F_SUF_DateStr2Date(t1.KCCKD1_KCJZSJ) AS KCCKD1_KCJZSJ,dbo.F_SUF_DateStr2Date(t1.KCCKD1_CHJZSJ) AS KCCKD1_CHJZSJ,t1.KCCKD1_SFQR
	,t1.KCCKD1_KCXM,t1.KCCKD1_ZJFX,t1.KCCKD1_DYPERSON,t1.KCCKD1_DYDATE,t1.KCCKD1_XELS,t1.KCCKD1_TDLS,t1.KCCKD1_JSBZ,t1.KCCKD1_C1
	,t1.KCCKD1_C2,t1.KCCKD1_C3,t1.KCCKD1_C4,t1.KCCKD1_C5,t1.KCCKD1_C6,t1.KCCKD1_C7,t1.KCCKD1_C8,t1.KCCKD1_C9,t1.KCCKD1_C10
	,t1.KCCKD1_U1,t1.KCCKD1_U2,t1.KCCKD1_U3,t1.KCCKD1_U4,t1.KCCKD1_U5,t1.KCCKD1_U6,t1.KCCKD1_GZZX,t1.KCCKD1_GXBH,t1.KCCKD1_FCRKDLS
	FROM KCCKD1 t1
GO

-- 库存出库单2
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCCKD2' AND xtype = 'V')
	DROP VIEW v_SUF_KCCKD2
GO
CREATE VIEW v_SUF_KCCKD2
AS
	SELECT t1.KCCKD2_PJLX,t1.KCCKD2_LSBH AS ID,t1.KCCKD2_FLBH AS EntryID,t1.KCCKD2_WLBH,t1.KCCKD2_TSKC,t1.KCCKD2_XGDX,t1.KCCKD2_DDLS,t1.KCCKD2_DDFL
	,t1.KCCKD2_WTLS,t1.KCCKD2_WTFL,t1.KCCKD2_QLLS,t1.KCCKD2_QLFL,t1.KCCKD2_HXSL,t1.KCCKD2_HXFSL1,t1.KCCKD2_HXFSL2,t1.KCCKD2_HXDJ
	,t1.KCCKD2_HXJE,t1.KCCKD2_GZZX,t1.KCCKD2_PCH,t1.KCCKD2_HWBH,t1.KCCKD2_ZYX1,t1.KCCKD2_ZYX2,t1.KCCKD2_ZYX3,t1.KCCKD2_ZYX4
	,t1.KCCKD2_ZYX5,t1.KCCKD2_WLZT,t1.KCCKD2_WLBZ,t1.KCCKD2_QLSL,t1.KCCKD2_SL,t1.KCCKD2_DJ,t1.KCCKD2_JE,t1.KCCKD2_FSL1,t1.KCCKD2_FSL2
	,t1.KCCKD2_TDLS,t1.KCCKD2_TDFL,t1.KCCKD2_XELS,t1.KCCKD2_XEFL,t1.KCCKD2_BZBH,t1.KCCKD2_GXBH,t1.KCCKD2_ZJZT,t1.KCCKD2_ZJJL
	,t1.KCCKD2_CLFS,t1.KCCKD2_ZJWC,t1.KCCKD2_JSSL,t1.KCCKD2_BGDH,t1.KCCKD2_BZ,t1.KCCKD2_FSL3,t1.KCCKD2_FQLSL,t1.KCCKD2_CXESL
	,t1.KCCKD2_CBBZ,t1.KCCKD2_THDZSL,t1.KCCKD2_THDJCSL,t1.KCCKD2_SCSQLS,t1.KCCKD2_SCSQFL,t1.KCCKD2_SCDDLS,t1.KCCKD2_SCDDFL
	,t1.KCCKD2_CGSQLS,t1.KCCKD2_CGSQFL,t1.KCCKD2_WXGDLS,t1.KCCKD2_WXGDFL,t1.KCCKD2_XSXH,t1.KCCKD2_C1,t1.KCCKD2_C2,t1.KCCKD2_C3
	,t1.KCCKD2_C4,t1.KCCKD2_C5,t1.KCCKD2_C6,t1.KCCKD2_C7,t1.KCCKD2_C8,t1.KCCKD2_C9,t1.KCCKD2_C10,t1.KCCKD2_U1,t1.KCCKD2_U2,t1.KCCKD2_U3
	,t1.KCCKD2_U4,t1.KCCKD2_U5,t1.KCCKD2_U6,t1.KCCKD2_GBDLS,t1.KCCKD2_GBDFL,t1.KCCKD2_TMH,t1.KCCKD2_XXH,t1.KCCKD2_GXLSBH,t1.KCCKD2_CKCY
	,t1.KCCKD2_PXBZ,t1.KCCKD2_CPBH,t1.KCCKD2_CPPC,t1.KCCKD2_CPSL,t1.KCCKD2_CLCBBZ
	,t1.KCCKD2_SL AS JBDWSL -- 基本单位数量
	,t2.LSWLZD_JLDW AS JLDW -- 计量单位
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	,NULL AS SCRQ
	FROM KCCKD2 t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.KCCKD2_WLBH=t2.LSWLZD_WLBH
GO

-- 生产订单
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_SCDD' AND xtype = 'V')
	DROP VIEW v_SUF_SCDD
GO
CREATE VIEW v_SUF_SCDD
AS
	SELECT t1.SCDD_LSBH AS ID,t1.SCDD_LX,t1.SCDD_DDBH,dbo.F_SUF_DateStr2Date(t1.SCDD_ZDRQ) AS SCDD_ZDRQ,t1.SCDD_ZDR,t1.SCDD_BZ,t1.SCDD_MRBMBH,t1.SCDD_MRLBBH,t1.SCDD_SHLC
	,t1.SCDD_SHBZ,t1.SCDD_SHRQ,t1.SCDD_SHXM,t1.SCDD_XSDD,t1.SCDD_KHMC,t1.SCDD_C1,t1.SCDD_C2,t1.SCDD_C3,t1.SCDD_C4,t1.SCDD_C5
	,t1.SCDD_C6,t1.SCDD_C7,t1.SCDD_C8,t1.SCDD_C9,t1.SCDD_C10,t1.SCDD_U1,t1.SCDD_U2,t1.SCDD_U3,t1.SCDD_U4,t1.SCDD_U5,t1.SCDD_U6
	,t1.SCDD_SFFG,t1.SCDD_YDDBH,t1.SCDD_YGXSXH,t1.SCDD_YGXBH,t1.SCDD_DYPERSON,t1.SCDD_DYDATE
	FROM SCDD t1
GO

-- 生产订单成品（作为生产订单明细）
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_SCDDCPMX' AND xtype = 'V')
	DROP VIEW v_SUF_SCDDCPMX
GO
CREATE VIEW v_SUF_SCDDCPMX
AS
	SELECT t1.SCDDCP_SCDDLSBH AS ID,t1.SCDDCP_LSBH AS EntryID,t1.SCDDCP_XH,t1.SCDDCP_DXLX,t1.SCDDCP_XGDX,t1.SCDDCP_XGDXLSBH,t1.SCDDCP_XGDXFLBH
	,t1.SCDDCP_WLBH,t1.SCDDCP_ZYX1,t1.SCDDCP_ZYX2,t1.SCDDCP_ZYX3,t1.SCDDCP_ZYX4,t1.SCDDCP_ZYX5,t1.SCDDCP_WLBZ,t1.SCDDCP_JHPCH
	,t1.SCDDCP_JHJH,t1.SCDDCP_GYLXLSBH,t1.SCDDCP_BOMLSBH,t1.SCDDCP_PZH,t1.SCDDCP_JHTCSL,t1.SCDDCP_YJCCSL,t1.SCDDCP_RKSL
	,t1.SCDDCP_JLDW,t1.SCDDCP_JE,dbo.F_SUF_DateStr2Date(t1.SCDDCP_JHTCRQ) AS SCDDCP_JHTCRQ,dbo.F_SUF_DateStr2Date(t1.SCDDCP_YJWGRQ) AS SCDDCP_YJWGRQ,dbo.F_SUF_DateStr2Date(t1.SCDDCP_SJKGRQ) AS SCDDCP_SJKGRQ,dbo.F_SUF_DateStr2Date(t1.SCDDCP_SJWGRQ) AS SCDDCP_SJWGRQ,t1.SCDDCP_GZZX,t1.SCDDCP_RCL
	,t1.SCDDCP_BMBH,t1.SCDDCP_LBBH,t1.SCDDCP_PCFS,t1.SCDDCP_YDFS,t1.SCDDCP_MRCK,t1.SCDDCP_ZT,t1.SCDDCP_LYLX,t1.SCDDCP_FGLX
	,t1.SCDDCP_LYDJBH,t1.SCDDCP_LYLSBH,t1.SCDDCP_LYFLBH,t1.SCDDCP_ZTYY,t1.SCDDCP_BGBZ,t1.SCDDCP_BGQLSBH,t1.SCDDCP_BGR,t1.SCDDCP_FLSBH
	,t1.SCDDCP_ZLSBH,t1.SCDDCP_FJSH,t1.SCDDCP_GXSH,t1.SCDDCP_ZXSH,t1.SCDDCP_BZ,t1.SCDDCP_C1,t1.SCDDCP_C2,t1.SCDDCP_C3,t1.SCDDCP_C4
	,t1.SCDDCP_C5,t1.SCDDCP_C6,t1.SCDDCP_C7,t1.SCDDCP_C8,t1.SCDDCP_C9,t1.SCDDCP_C10,t1.SCDDCP_U1,t1.SCDDCP_U2,t1.SCDDCP_U3
	,t1.SCDDCP_U4,t1.SCDDCP_U5,t1.SCDDCP_U6,t1.SCDDCP_ZXXSCS,t1.SCDDCP_ZXZDSC,t1.SCDDCP_ZXSCBOM,t1.SCDDCP_DYPERSON,t1.SCDDCP_DYDATE
	,t1.SCDDCP_SFFG,t1.SCDDCP_YLSBH,t1.SCDDCP_ZDRQ
	,t1.SCDDCP_YJCCSL AS JBDWSL -- 基本单位数量
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	FROM SCDDCP t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.SCDDCP_WLBH=t2.LSWLZD_WLBH
GO

-- 库存入库单1
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCRKD1' AND xtype = 'V')
	DROP VIEW v_SUF_KCRKD1
GO
CREATE VIEW v_SUF_KCRKD1
AS
	SELECT t1.KCRKD1_PJLX,t1.KCRKD1_LSBH AS ID,dbo.F_SUF_DateStr2Date(t1.KCRKD1_DJRQ) AS KCRKD1_DJRQ,dbo.F_SUF_DateStr2Date(t1.KCRKD1_KCYWRQ) AS KCRKD1_KCYWRQ,dbo.F_SUF_DateStr2Date(t1.KCRKD1_CHYWRQ) AS KCRKD1_CHYWRQ,t1.KCRKD1_SJDH,t1.KCRKD1_LBBH
	,t1.KCRKD1_CKBH,t1.KCRKD1_DWBH,t1.KCRKD1_DDBH,t1.KCRKD1_JHBH,t1.KCRKD1_BMBH,t1.KCRKD1_ZGBH,t1.KCRKD1_JKY,t1.KCRKD1_FZR
	,t1.KCRKD1_BGY,t1.KCRKD1_LRXM,t1.KCRKD1_SFJCHZ,t1.KCRKD1_BZ,t1.KCRKD1_ZJDH,t1.KCRKD1_SHLC,t1.KCRKD1_SHBZ,t1.KCRKD1_SHRQ
	,t1.KCRKD1_SHXM,t1.KCRKD1_CGJZ,t1.KCRKD1_SFCZGJ,t1.KCRKD1_CGRQ,t1.KCRKD1_KCJZ,t1.KCRKD1_CHJZ,t1.KCRKD1_CHXM,t1.KCRKD1_FPHX
	,t1.KCRKD1_CYFPHX,t1.KCRKD1_CXBZ,t1.KCRKD1_QCBZ,t1.KCRKD1_HDBZ,t1.KCRKD1_CXBH,t1.KCRKD1_ZGBZ,dbo.F_SUF_DateStr2Date(t1.KCRKD1_PZRQ) AS KCRKD1_PZRQ,t1.KCRKD1_PZNM
	,t1.KCRKD1_PZND,t1.KCRKD1_PZBH,t1.KCRKD1_DYPERSON,t1.KCRKD1_DYDATE,t1.KCRKD1_YWBS,t1.KCRKD1_LYBH,t1.KCRKD1_SCDH
	,t1.KCRKD1_CJJZ,dbo.F_SUF_DateStr2Date(t1.KCRKD1_CJRQ) AS KCRKD1_CJRQ,t1.KCRKD1_CJXM,t1.KCRKD1_CBBZ,t1.KCRKD1_DCBZ,t1.KCRKD1_DWGC,dbo.F_SUF_DateStr2Date(t1.KCRKD1_KCXGSJ) AS KCRKD1_KCXGSJ,dbo.F_SUF_DateStr2Date(t1.KCRKD1_CHXGSJ) AS KCRKD1_CHXGSJ
	,dbo.F_SUF_DateStr2Date(t1.KCRKD1_KCJZSJ) AS KCRKD1_KCJZSJ,dbo.F_SUF_DateStr2Date(t1.KCRKD1_CHJZSJ) AS KCRKD1_CHJZSJ,t1.KCRKD1_SFQR,t1.KCRKD1_KCXM,t1.KCRKD1_ZJFX,t1.KCRKD1_C1,t1.KCRKD1_C2,t1.KCRKD1_C4
	,t1.KCRKD1_C3,t1.KCRKD1_C5,t1.KCRKD1_C6,t1.KCRKD1_C7,t1.KCRKD1_C8,t1.KCRKD1_C9,t1.KCRKD1_C10,t1.KCRKD1_U1,t1.KCRKD1_U2
	,t1.KCRKD1_U3,t1.KCRKD1_U4,t1.KCRKD1_U5,t1.KCRKD1_U6,t1.KCRKD1_YLZZS,t1.KCRKD1_DDJSF,t1.KCRKD1_HWTGF,t1.KCRKD1_SKF
	,t1.KCRKD1_KPF,t1.KCRKD1_ZFYW,t1.KCRKD1_SCFLAG,t1.KCRKD1_FCBZ
	FROM KCRKD1 t1
GO

-- 库存入库单2
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCRKD2' AND xtype = 'V')
	DROP VIEW v_SUF_KCRKD2
GO
CREATE VIEW v_SUF_KCRKD2
AS
	SELECT t1.KCRKD2_PJLX,t1.KCRKD2_LSBH AS ID,t1.KCRKD2_FLBH AS EntryID,t1.KCRKD2_WLBH,t1.KCRKD2_TSKC,t1.KCRKD2_XGDX,t1.KCRKD2_DDLS,t1.KCRKD2_DDFL
	,t1.KCRKD2_DHLS,t1.KCRKD2_DHFL,t1.KCRKD2_JHLS,t1.KCRKD2_JHFL,t1.KCRKD2_CGDDLS,t1.KCRKD2_CGDDFL,t1.KCRKD2_WTDDFL,t1.KCRKD2_JHBH
	,t1.KCRKD2_YSSL,t1.KCRKD2_SSSL,t1.KCRKD2_HLSH,t1.KCRKD2_DJ,t1.KCRKD2_JE,t1.KCRKD2_JHDJ,t1.KCRKD2_JHJE,t1.KCRKD2_HSDJ
	,t1.KCRKD2_SL,t1.KCRKD2_SE,t1.KCRKD2_HSJE,t1.KCRKD2_FYSSL1,t1.KCRKD2_FYSSL2,t1.KCRKD2_FSSSL1,t1.KCRKD2_FSSSL2,t1.KCRKD2_PCH
	,t1.KCRKD2_HWBH,t1.KCRKD2_ZYX1,t1.KCRKD2_ZYX2,t1.KCRKD2_ZYX3,t1.KCRKD2_ZYX4,t1.KCRKD2_ZYX5,t1.KCRKD2_WLZT,t1.KCRKD2_WLBZ
	,t1.KCRKD2_HXSL,t1.KCRKD2_HXDJ,t1.KCRKD2_HXJE,t1.KCRKD2_CLJE,t1.KCRKD2_JGJE,t1.KCRKD2_YZJE,t1.KCRKD2_WTCBBZ,t1.KCRKD2_ZJZT
	,t1.KCRKD2_ZJJL,t1.KCRKD2_CLFS,t1.KCRKD2_ZJWC,t1.KCRKD2_JSSL,t1.KCRKD2_BGDH,t1.KCRKD2_BZ,t1.KCRKD2_ZLDH,t1.KCRKD2_FYSSL3
	,t1.KCRKD2_FSSSL3,t1.KCRKD2_RKJLLS,t1.KCRKD2_RKJLFL,t1.KCRKD2_SCDDLS,t1.KCRKD2_SCDDFL,t1.KCRKD2_C1,t1.KCRKD2_C2,t1.KCRKD2_C3
	,t1.KCRKD2_C4,t1.KCRKD2_C5,t1.KCRKD2_C6,t1.KCRKD2_C7,t1.KCRKD2_C8,t1.KCRKD2_C9,t1.KCRKD2_C10,t1.KCRKD2_U1,t1.KCRKD2_U2
	,t1.KCRKD2_U3,t1.KCRKD2_U4,t1.KCRKD2_U5,t1.KCRKD2_U6,t1.KCRKD2_XSXH,t1.KCRKD2_CXLS,t1.KCRKD2_CXFL,t1.KCRKD2_THSL,t1.KCRKD2_THFSL1
	,t1.KCRKD2_THFSL2,t1.KCRKD2_CGDDBH,t1.KCRKD2_GBDLS,t1.KCRKD2_GBDFL,t1.KCRKD2_TMH,t1.KCRKD2_XXH,t1.KCRKD2_HXHSJE,t1.KCRKD2_GZZX
	,t1.KCRKD2_GXBH,t1.KCRKD2_GXLSBH,t1.KCRKD2_PXBZ,t1.KCRKD2_CLCBBZ
	,t1.KCRKD2_SSSL AS JBDWSL -- 基本单位数量
	,t2.LSWLZD_JLDW AS JLDW -- 计量单位
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	,NULL AS SCRQ
	FROM KCRKD2 t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.KCRKD2_WLBH=t2.LSWLZD_WLBH
GO

-- 生产订单成品
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_SCDDCP' AND xtype = 'V')
	DROP VIEW v_SUF_SCDDCP
GO
CREATE VIEW v_SUF_SCDDCP
AS
	SELECT t1.SCDDCP_SCDDLSBH,t1.SCDDCP_LSBH AS ID,t1.SCDDCP_XH,t1.SCDDCP_DXLX,t1.SCDDCP_XGDX,t1.SCDDCP_XGDXLSBH,t1.SCDDCP_XGDXFLBH
	,t1.SCDDCP_WLBH,t1.SCDDCP_ZYX1,t1.SCDDCP_ZYX2,t1.SCDDCP_ZYX3,t1.SCDDCP_ZYX4,t1.SCDDCP_ZYX5,t1.SCDDCP_WLBZ,t1.SCDDCP_JHPCH
	,t1.SCDDCP_JHJH,t1.SCDDCP_GYLXLSBH,t1.SCDDCP_BOMLSBH,t1.SCDDCP_PZH,t1.SCDDCP_JHTCSL,t1.SCDDCP_YJCCSL,t1.SCDDCP_RKSL
	,t1.SCDDCP_JLDW,t1.SCDDCP_JE,dbo.F_SUF_DateStr2Date(t1.SCDDCP_JHTCRQ) AS SCDDCP_JHTCRQ,dbo.F_SUF_DateStr2Date(t1.SCDDCP_YJWGRQ) AS SCDDCP_YJWGRQ,dbo.F_SUF_DateStr2Date(t1.SCDDCP_SJKGRQ) AS SCDDCP_SJKGRQ,dbo.F_SUF_DateStr2Date(t1.SCDDCP_SJWGRQ) AS SCDDCP_SJWGRQ,t1.SCDDCP_GZZX,t1.SCDDCP_RCL
	,t1.SCDDCP_BMBH,t1.SCDDCP_LBBH,t1.SCDDCP_PCFS,t1.SCDDCP_YDFS,t1.SCDDCP_MRCK,t1.SCDDCP_ZT,t1.SCDDCP_LYLX,t1.SCDDCP_FGLX
	,t1.SCDDCP_LYDJBH,t1.SCDDCP_LYLSBH,t1.SCDDCP_LYFLBH,t1.SCDDCP_ZTYY,t1.SCDDCP_BGBZ,t1.SCDDCP_BGQLSBH,t1.SCDDCP_BGR,t1.SCDDCP_FLSBH
	,t1.SCDDCP_ZLSBH,t1.SCDDCP_FJSH,t1.SCDDCP_GXSH,t1.SCDDCP_ZXSH,t1.SCDDCP_BZ,t1.SCDDCP_C1,t1.SCDDCP_C2,t1.SCDDCP_C3,t1.SCDDCP_C4
	,t1.SCDDCP_C5,t1.SCDDCP_C6,t1.SCDDCP_C7,t1.SCDDCP_C8,t1.SCDDCP_C9,t1.SCDDCP_C10,t1.SCDDCP_U1,t1.SCDDCP_U2,t1.SCDDCP_U3
	,t1.SCDDCP_U4,t1.SCDDCP_U5,t1.SCDDCP_U6,t1.SCDDCP_ZXXSCS,t1.SCDDCP_ZXZDSC,t1.SCDDCP_ZXSCBOM,t1.SCDDCP_DYPERSON,t1.SCDDCP_DYDATE
	,t1.SCDDCP_SFFG,t1.SCDDCP_YLSBH,t1.SCDDCP_ZDRQ
	,t1.SCDDCP_YJCCSL AS JBDWSL -- 基本单位数量
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,t3.SCDD_DDBH -- 生产订单订单编号
	,t3.SCDD_SHBZ -- 生产订单审核标志
	,dbo.F_SUF_DateStr2Date(t3.SCDD_ZDRQ) AS SCDD_ZDRQ --生产订单制单日期
	,'' AS _id_
	,'' AS _entryId_
	FROM SCDDCP t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.SCDDCP_WLBH=t2.LSWLZD_WLBH
	LEFT JOIN SCDD t3 ON t3.SCDD_LSBH=t1.SCDDCP_SCDDLSBH
GO

-- 生产订单子项
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_SCDDZX' AND xtype = 'V')
	DROP VIEW v_SUF_SCDDZX
GO
CREATE VIEW v_SUF_SCDDZX
AS
	SELECT t4.SCDD_LSBH AS ID,(t1.SCDDZX_LSBH + '#' + t1.SCDDZX_FLBH )AS EntryID /*生产订单子项设置组合主键,用#隔开*/
	,t1.SCDDZX_LSBH,t1.SCDDZX_FLBH,t1.SCDDZX_ZXLX,t1.SCDDZX_GXBH,t1.SCDDZX_GZZX
	,dbo.F_SUF_DateStr2Date(t1.SCDDZX_XQRQ) AS SCDDZX_XQRQ,t1.SCDDZX_BOMLS,t1.SCDDZX_WLBH
	,t1.SCDDZX_ZYX1,t1.SCDDZX_ZYX2,t1.SCDDZX_ZYX3,t1.SCDDZX_ZYX4,t1.SCDDZX_ZYX5,t1.SCDDZX_SL,t1.SCDDZX_JLDW,t1.SCDDZX_SHL
	,t1.SCDDZX_BL,t1.SCDDZX_DL,t1.SCDDZX_GYLX,t1.SCDDZX_GYCK,t1.SCDDZX_GYHW,t1.SCDDZX_TDBZ,t1.SCDDZX_YLSL,t1.SCDDZX_WQRYLSL,t1.SCDDZX_TDSL
	,t1.SCDDZX_TDFL,t1.SCDDZX_TDBL,t1.SCDDZX_YJKYL,t1.SCDDZX_DBSL,t1.SCDDZX_BZ,t1.SCDDZX_C1,t1.SCDDZX_C2,t1.SCDDZX_C3
	,t1.SCDDZX_C4,t1.SCDDZX_C5,t1.SCDDZX_C6,t1.SCDDZX_C7,t1.SCDDZX_C8,t1.SCDDZX_C9,t1.SCDDZX_C10,t1.SCDDZX_U1,t1.SCDDZX_U2
	,t1.SCDDZX_U3,t1.SCDDZX_U4,t1.SCDDZX_U5,t1.SCDDZX_U6,t1.SCDDZX_KCFS,t1.SCDDZX_DDLS,t1.SCDDZX_DDFL,t1.SCDDZX_WLBZ
	,t1.SCDDZX_PZBH,t1.SCDDZX_XH,t1.SCDDZX_XE,t1.SCDDZX_CCCBBDBL,t1.SCDDZX_CCCBGDDJ,t1.SCDDZX_CCCBJE,t1.SCDDZX_XNWLBH
	,t1.SCDDZX_XNWLDB,t1.SCDDZX_YXBH,t1.SCDDZX_YKSL
	,t1.SCDDZX_SL AS JBDWSL -- 基本单位数量
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	FROM SCDDZX t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.SCDDZX_WLBH=t2.LSWLZD_WLBH
	LEFT JOIN SCDDCP t3 ON t1.SCDDZX_LSBH = t3.SCDDCP_LSBH
	LEFT JOIN SCDD t4 ON t3.SCDDCP_SCDDLSBH = t4.SCDD_LSBH
GO

-- 采购订单表头
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_CGDD1' AND xtype = 'V')
	DROP VIEW v_SUF_CGDD1
GO
CREATE VIEW v_SUF_CGDD1
AS
	SELECT t1.CGDD1_LSBH AS ID,t1.CGDD1_LYBZ,t1.CGDD1_SJDH,dbo.F_SUF_DateStr2Date(t1.CGDD1_YWRQ) AS CGDD1_YWRQ,dbo.F_SUF_DateStr2Date(t1.CGDD1_DJRQ) AS CGDD1_DJRQ,dbo.F_SUF_DateStr2Date(t1.CGDD1_XGSJ) AS CGDD1_XGSJ,t1.CGDD1_DDMC,t1.CGDD1_DDLX
	,t1.CGDD1_YLZZS,t1.CGDD1_HWTGF,t1.CGDD1_DDJSF,t1.CGDD1_SKF,t1.CGDD1_KPF,t1.CGDD1_LBBH,t1.CGDD1_WBBH,t1.CGDD1_HL,t1.CGDD1_YFDJ
	,t1.CGDD1_ZKBH,t1.CGDD1_JSFS,t1.CGDD1_BMBH,t1.CGDD1_ZGBH,t1.CGDD1_QDDD,t1.CGDD1_DFDB,t1.CGDD1_LRXM,t1.CGDD1_BZ,t1.CGDD1_SHLC
	,dbo.F_SUF_DateStr2Date(t1.CGDD1_SHRQ) AS CGDD1_SHRQ,t1.CGDD1_SHXM,t1.CGDD1_SHBZ,t1.CGDD1_ZTBZ,dbo.F_SUF_DateStr2Date(t1.CGDD1_JZRQ) AS CGDD1_JZRQ,t1.CGDD1_YBHXJE,t1.CGDD1_BBHXJE,t1.CGDD1_DYDATE
	,t1.CGDD1_DYPERSON,t1.CGDD1_DDBZ,t1.CGDD1_SFCZGJ,t1.CGDD1_C1,t1.CGDD1_C2,t1.CGDD1_C3,t1.CGDD1_C4,t1.CGDD1_C5,t1.CGDD1_C6
	,t1.CGDD1_C7,t1.CGDD1_C8,t1.CGDD1_C9,t1.CGDD1_C10,t1.CGDD1_U1,t1.CGDD1_U2,t1.CGDD1_U3,t1.CGDD1_U4,t1.CGDD1_U6,t1.CGDD1_U5
	,t1.CGDD1_DWGC,t1.CGDD1_LZGZBH
	FROM CGDD1 t1
GO

-- 采购订单表体
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_CGDD2' AND xtype = 'V')
	DROP VIEW v_SUF_CGDD2
GO
CREATE VIEW v_SUF_CGDD2
AS
	SELECT t1.CGDD2_LSBH AS ID,t1.CGDD2_FLH AS EntryID,dbo.F_SUF_DateStr2Date(t1.CGDD2_YDRQ) AS CGDD2_YDRQ,t1.CGDD2_WLBH,t1.CGDD2_CKBH,t1.CGDD2_ZYX1,t1.CGDD2_ZYX2,t1.CGDD2_ZYX3
	,t1.CGDD2_ZYX4,t1.CGDD2_ZYX5,t1.CGDD2_FLLX,t1.CGDD2_XMBH,t1.CGDD2_DDLS,t1.CGDD2_DDFL,t1.CGDD2_SL,t1.CGDD2_FSL1
	,t1.CGDD2_FSL2,t1.CGDD2_DJ,t1.CGDD2_YBJE,t1.CGDD2_BBJE,t1.CGDD2_LJSL,t1.CGDD2_PJDJ,t1.CGDD2_YBLJJE,t1.CGDD2_BBLJJE
	,t1.CGDD2_JXSL,dbo.F_SUF_DateStr2Date(t1.CGDD2_SDRQ) AS CGDD2_SDRQ,t1.CGDD2_ZTSL,t1.CGDD2_YFSL,t1.CGDD2_YFF,t1.CGDD2_YCBL,t1.CGDD2_DHSL,t1.CGDD2_THSL
	,t1.CGDD2_QGDLS,t1.CGDD2_QGDFL,t1.CGDD2_WGSL,t1.CGDD2_KPSL,t1.CGDD2_HTLS,t1.CGDD2_HTFL,t1.CGDD2_JHLS,t1.CGDD2_JHFL
	,t1.CGDD2_SCDDLS,t1.CGDD2_GXJHLS,t1.CGDD2_SCDDBOMLS,t1.CGDD2_GXBH,t1.CGDD2_TZSL,t1.CGDD2_TZFSL1,t1.CGDD2_TZFSL2
	,t1.CGDD2_YTZE,t1.CGDD2_BTZE,t1.CGDD2_YDDLS,t1.CGDD2_YDDFL,t1.CGDD2_YDDBH,t1.CGDD2_YBHSJE,t1.CGDD2_BBHSJE,t1.CGDD2_HSDJ
	,t1.CGDD2_YBSE,t1.CGDD2_BBSE,t1.CGDD2_KPFSL1,t1.CGDD2_KPFSL2,t1.CGDD2_YKPE,t1.CGDD2_BKPE,t1.CGDD2_C1,t1.CGDD2_C2
	,t1.CGDD2_C3,t1.CGDD2_C4,t1.CGDD2_C5,t1.CGDD2_C6,t1.CGDD2_C7,t1.CGDD2_C8,t1.CGDD2_C9,t1.CGDD2_C10,t1.CGDD2_U1,t1.CGDD2_U2
	,t1.CGDD2_U3,t1.CGDD2_U4,t1.CGDD2_U6,t1.CGDD2_U5,t1.CGDD2_BZ,t1.CGDD2_SPDLS,t1.CGDD2_SPDFL,t1.CGDD2_ZTBZ,t1.CGDD2_GXZYDLS
	,t1.CGDD2_GXZYDBH,t1.CGDD2_XSXH,t1.CGDD2_GBSL,t1.CGDD2_GZZX
	,t1.CGDD2_SL AS JBDWSL -- 基本单位数量
	,t2.LSWLZD_JLDW AS JLDW -- 计量单位
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	,'' AS FStatus -- 【LC】状态特殊字段，此字段需要在查询时做特殊处理来进行数据填充
	FROM CGDD2 t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.CGDD2_WLBH=t2.LSWLZD_WLBH
GO

-- 库存盘点表表头
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCYXZ1' AND xtype = 'V')
	DROP VIEW v_SUF_KCYXZ1
GO
CREATE VIEW v_SUF_KCYXZ1
AS
    SELECT t1.KCYXZ1_LSBH AS ID,t1.KCYXZ1_PJLX,dbo.F_SUF_DateStr2Date(t1.KCYXZ1_DJRQ) AS KCYXZ1_DJRQ,dbo.F_SUF_DateStr2Date(t1.KCYXZ1_CKYWRQ) AS KCYXZ1_CKYWRQ
    ,dbo.F_SUF_DateStr2Date(t1.KCYXZ1_RKYWRQ) AS KCYXZ1_RKYWRQ,t1.KCYXZ1_LYYT,t1.KCYXZ1_TDBH,t1.KCYXZ1_TDLS,t1.KCYXZ1_CXBH,t1.KCYXZ1_DWMC
    ,t1.KCYXZ1_DWBH,t1.KCYXZ1_DHDD,t1.KCYXZ1_GXTD,t1.KCYXZ1_HDBZ,t1.KCYXZ1_QCBZ,t1.KCYXZ1_SJDH,t1.KCYXZ1_YCCK,t1.KCYXZ1_YRCK,t1.KCYXZ1_BMBH,t1.KCYXZ1_YRBM,t1.KCYXZ1_RKLBBH
    ,t1.KCYXZ1_CKLBBH,t1.KCYXZ1_YKY,t1.KCYXZ1_YRY,t1.KCYXZ1_PZR,t1.KCYXZ1_LRXM,t1.KCYXZ1_BZ,t1.KCYXZ1_CKJZ,t1.KCYXZ1_CKXM,t1.KCYXZ1_RKJZ,t1.KCYXZ1_RKXM,dbo.F_SUF_DateStr2Date(t1.KCYXZ1_PZRQ) AS KCYXZ1_PZRQ
    ,t1.KCYXZ1_PZNM,t1.KCYXZ1_PZND,t1.KCYXZ1_PZBH,t1.KCYXZ1_SHBZ,t1.KCYXZ1_SHLC,t1.KCYXZ1_SHXM,t1.KCYXZ1_SHRQ,t1.KCYXZ1_YWBS,t1.KCYXZ1_SFJCHZ,dbo.F_SUF_DateStr2Date(t1.KCYXZ1_KCXGSJ) AS KCYXZ1_KCXGSJ
    ,dbo.F_SUF_DateStr2Date(t1.KCYXZ1_RKJZSJ) AS KCYXZ1_RKJZSJ,dbo.F_SUF_DateStr2Date(t1.KCYXZ1_CKJZSJ) AS KCYXZ1_CKJZSJ,t1.KCYXZ1_DYPERSON,t1.KCYXZ1_DYDATE,t1.KCYXZ1_SFQR,t1.KCYXZ1_C1,t1.KCYXZ1_C2,t1.KCYXZ1_C3,t1.KCYXZ1_C4,t1.KCYXZ1_C5,t1.KCYXZ1_C6
    ,t1.KCYXZ1_C7,t1.KCYXZ1_C8,t1.KCYXZ1_C9,t1.KCYXZ1_C10,t1.KCYXZ1_U1,t1.KCYXZ1_U2,t1.KCYXZ1_U3,t1.KCYXZ1_U4,t1.KCYXZ1_U5,t1.KCYXZ1_U6
    FROM KCYXZ1 t1
GO

-- 库存盘点表表体
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_KCYXZ2' AND xtype = 'V')
	DROP VIEW v_SUF_KCYXZ2
GO
CREATE VIEW v_SUF_KCYXZ2
AS
    SELECT t1.KCYXZ2_LSBH AS ID,t1.KCYXZ2_FLBH AS EntryID,t1.KCYXZ2_PJLX,t1.KCYXZ2_FLZT,t1.KCYXZ2_WLBH,t1.KCYXZ2_PCH,t1.KCYXZ2_HWBH,t1.KCYXZ2_TSKC,t1.KCYXZ2_XGDX,t1.KCYXZ2_DDLS
    ,t1.KCYXZ2_DDFL,t1.KCYXZ2_WTDDLS,t1.KCYXZ2_WTDDFL,t1.KCYXZ2_QGDLS,t1.KCYXZ2_QGDFL,t1.KCYXZ2_TDFL,t1.KCYXZ2_TDLS,t1.KCYXZ2_ZYX1,t1.KCYXZ2_ZYX2,t1.KCYXZ2_ZYX3
    ,t1.KCYXZ2_ZYX4,t1.KCYXZ2_ZYX5,t1.KCYXZ2_WLZT,t1.KCYXZ2_WLBZ,t1.KCYXZ2_JHBH,t1.KCYXZ2_SL,t1.KCYXZ2_FSL1,t1.KCYXZ2_FSL2,t1.KCYXZ2_DJ,t1.KCYXZ2_JE,t1.KCYXZ2_YRHW
    ,t1.KCYXZ2_RKSL,t1.KCYXZ2_FRKSL1,t1.KCYXZ2_FRKSL2,t1.KCYXZ2_RKDJ,t1.KCYXZ2_RKJE,t1.KCYXZ2_SLCY,t1.KCYXZ2_JECY,t1.KCYXZ2_DJCY,t1.KCYXZ2_CYYY,t1.KCYXZ2_HXSL
    ,t1.KCYXZ2_BZ,t1.KCYXZ2_TZDLS,t1.KCYXZ2_TZDFL,t1.KCYXZ2_XSXH,t1.KCYXZ2_YRTSKC,t1.KCYXZ2_YRXGDX,t1.KCYXZ2_YRDDLS,t1.KCYXZ2_YRDDFL,t1.KCYXZ2_C1,t1.KCYXZ2_C2
    ,t1.KCYXZ2_C3,t1.KCYXZ2_C4,t1.KCYXZ2_C5,t1.KCYXZ2_C6,t1.KCYXZ2_C7,t1.KCYXZ2_C8,t1.KCYXZ2_C9,t1.KCYXZ2_C10,t1.KCYXZ2_U1,t1.KCYXZ2_U2,t1.KCYXZ2_U3,t1.KCYXZ2_U4
    ,t1.KCYXZ2_U5,t1.KCYXZ2_U6,t1.KCYXZ2_GBDLS,t1.KCYXZ2_GBDFL,t1.KCYXZ2_LLSQLS,t1.KCYXZ2_LLSQFL,t1.KCYXZ2_RKDLS,t1.KCYXZ2_RKDFL,t1.KCYXZ2_ZYDLS,t1.KCYXZ2_ZYDFL
    ,t1.KCYXZ2_SCDDLS,t1.KCYXZ2_SCDDFL,t1.KCYXZ2_TMH
    ,t1.KCYXZ2_SL AS JBDWSL -- 基本单位数量
	,t2.LSWLZD_JLDW AS JLDW -- 计量单位
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	,NULL AS SCRQ
    FROM KCYXZ2 t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.KCYXZ2_WLBH=t2.LSWLZD_WLBH
GO


-- 采购到货单表头
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_CGDHD1' AND xtype = 'V')
	DROP VIEW v_SUF_CGDHD1
GO
CREATE VIEW v_SUF_CGDHD1
AS
	SELECT t1.CGDHD1_LSBH AS ID,t1.CGDHD1_PJLX,t1.CGDHD1_HDBZ,dbo.F_SUF_DateStr2Date(t1.CGDHD1_DJRQ) AS CGDHD1_DJRQ
	,dbo.F_SUF_DateStr2Date(t1.CGDHD1_DHRQ) AS CGDHD1_DHRQ,t1.CGDHD1_DJBH,t1.CGDHD1_CXBH,t1.CGDHD1_LYBZ,t1.CGDHD1_CGSJ,t1.CGDHD1_YLZZS
	,t1.CGDHD1_HWTGF,t1.CGDHD1_DDJSF,t1.CGDHD1_SKF,t1.CGDHD1_KPF,t1.CGDHD1_WBBH,t1.CGDHD1_HL
	,t1.CGDHD1_BMBH,t1.CGDHD1_ZGBH,t1.CGDHD1_ZDXM,t1.CGDHD1_YSFS,t1.CGDHD1_SFQR,t1.CGDHD1_DYPERSON
	,t1.CGDHD1_DYDATE,t1.CGDHD1_BZ,t1.CGDHD1_ZJFX,t1.CGDHD1_KPBZ,t1.CGDHD1_C1,t1.CGDHD1_C2,t1.CGDHD1_C3
	,t1.CGDHD1_C4,t1.CGDHD1_C5,t1.CGDHD1_C6,t1.CGDHD1_C7,t1.CGDHD1_C8,t1.CGDHD1_C9,t1.CGDHD1_C10
	,t1.CGDHD1_U1,t1.CGDHD1_U2,t1.CGDHD1_U3,t1.CGDHD1_U4,t1.CGDHD1_U5,t1.CGDHD1_U6,t1.CGDHD1_DWGC
	,t1.CGDHD1_SHLC,t1.CGDHD1_SHXM,t1.CGDHD1_SHBZ
	,dbo.F_SUF_DateStr2Date(t1.CGDHD1_SHRQ) AS CGDHD1_SHRQ
	FROM CGDHD1 t1
GO

-- 采购到货单表体
IF EXISTS(SELECT 1 FROM sysobjects WHERE name = 'v_SUF_CGDHD2' AND xtype = 'V')
	DROP VIEW v_SUF_CGDHD2
GO
CREATE VIEW v_SUF_CGDHD2
AS
	SELECT t1.CGDHD2_LSBH AS ID,t1.CGDHD2_FLBH AS EntryID,t1.CGDHD2_PJLX,t1.CGDHD2_CXLS,t1.CGDHD2_CXFL,t1.CGDHD2_WLBH
	,t1.CGDHD2_FLLX,t1.CGDHD2_XGDX,t1.CGDHD2_PCH,t1.CGDHD2_WLBZ,t1.CGDHD2_WLZT,t1.CGDHD2_ZYX1
	,t1.CGDHD2_ZYX2,t1.CGDHD2_ZYX3,t1.CGDHD2_ZYX4,t1.CGDHD2_ZYX5,t1.CGDHD2_CKBH,t1.CGDHD2_HWBH
	,t1.CGDHD2_YSSL,t1.CGDHD2_FYSSL1,t1.CGDHD2_FYSSL2,t1.CGDHD2_SSSL,t1.CGDHD2_FSSSL1,t1.CGDHD2_FSSSL2
	,t1.CGDHD2_JSSL,t1.CGDHD2_FJSSL1,t1.CGDHD2_FJSSL2,t1.CGDHD2_DJ,t1.CGDHD2_HSDJ,t1.CGDHD2_TAXRATE
	,t1.CGDHD2_JE,t1.CGDHD2_HSJE,t1.CGDHD2_BBJE,t1.CGDHD2_BBHSJE,t1.CGDHD2_JHLS,t1.CGDHD2_JHFL
	,t1.CGDHD2_DDLS,t1.CGDHD2_DDFL,t1.CGDHD2_RKSL,t1.CGDHD2_FRKSL1,t1.CGDHD2_FRKSL2,t1.CGDHD2_THSL
	,t1.CGDHD2_FTHSL1,t1.CGDHD2_FTHSL2,t1.CGDHD2_ZJZT,t1.CGDHD2_ZJJL,t1.CGDHD2_CLFS,t1.CGDHD2_ZJWC
	,t1.CGDHD2_BGDH,t1.CGDHD2_CGDDLS,t1.CGDHD2_CGDDFL,t1.CGDHD2_SFZJ,t1.CGDHD2_C1,t1.CGDHD2_C2
	,t1.CGDHD2_C3,t1.CGDHD2_C4,t1.CGDHD2_C5,t1.CGDHD2_C6,t1.CGDHD2_C7,t1.CGDHD2_C8,t1.CGDHD2_C9
	,t1.CGDHD2_C10,t1.CGDHD2_U1,t1.CGDHD2_U2,t1.CGDHD2_U3,t1.CGDHD2_U4,t1.CGDHD2_U6,t1.CGDHD2_U5
	,t1.CGDHD2_JHDJ,t1.CGDHD2_JHJE,t1.CGDHD2_KXSL,t1.CGDHD2_GXZYDLS,t1.CGDHD2_GXZYDBH,t1.CGDHD2_GXSL
	,t1.CGDHD2_GXFSL1,t1.CGDHD2_GXFSL2,t1.CGDHD2_FXSL,t1.CGDHD2_KPSL,t1.CGDHD2_KPFSL1,t1.CGDHD2_KPFSL2
	,t1.CGDHD2_YBKPJE,t1.CGDHD2_BBKPJE,t1.CGDHD2_KPBZ,t1.CGDHD2_XSXH,t1.CGDHD2_GBSL,t1.CGDHD2_YSSSL,t1.CGDHD2_HTLS
	,t1.CGDHD2_HTFL,t1.CGDHD2_JSKZ,t1.CGDHD2_GXBH,t1.CGDHD2_GZZX
	,t1.CGDHD2_SSSL AS JBDWSL -- 基本单位数量
	,t2.LSWLZD_JLDW AS JLDW -- 计量单位
	,t2.JBJLDW AS JBJLDW -- 基本计量单位
	,'' AS _id_
	,'' AS _entryId_
	,'' AS FStatus -- 【LC】状态特殊字段，此字段需要在查询时做特殊处理来进行数据填充
	FROM CGDHD2 t1
	LEFT JOIN v_SUF_LSWLZD t2 ON t1.CGDHD2_WLBH=t2.LSWLZD_WLBH
GO

